name: Pack Image to Release

on:
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # 赋予创建 Release 的写入权限
    steps:
      - name: Pull and Save Image
        run: |
          # 1. 拉取官方精准镜像
          docker pull collabora/code:25.04.9.4.1
          
          # 2. 导出为本地离线 tar 包
          docker save -o collabora-code.tar collabora/code:25.04.9.4.1
          
          # 3. 压缩以加快后续下载速度
          tar -czf bcc.tar.gz collabora-code.tar

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v25.04.9.4.1
          name: Collabora Online Image Release
          files: bcc.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
